//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.RoomAvailbilityServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomAvailbilityServiceReference.RoomAvailabilitySoap")]
    public interface RoomAvailabilitySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomRoomCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindRoomRoomCountry(string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomRoomCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FindRoomRoomCountryAsync(string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomRoomId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindRoomRoomId(string RoomId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomRoomId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FindRoomRoomIdAsync(string RoomId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoomAvailabilitySoapChannel : ClientApplication.RoomAvailbilityServiceReference.RoomAvailabilitySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomAvailabilitySoapClient : System.ServiceModel.ClientBase<ClientApplication.RoomAvailbilityServiceReference.RoomAvailabilitySoap>, ClientApplication.RoomAvailbilityServiceReference.RoomAvailabilitySoap {
        
        public RoomAvailabilitySoapClient() {
        }
        
        public RoomAvailabilitySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomAvailabilitySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomAvailabilitySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomAvailabilitySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FindRoomRoomCountry(string Country) {
            return base.Channel.FindRoomRoomCountry(Country);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FindRoomRoomCountryAsync(string Country) {
            return base.Channel.FindRoomRoomCountryAsync(Country);
        }
        
        public System.Data.DataSet FindRoomRoomId(string RoomId) {
            return base.Channel.FindRoomRoomId(RoomId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FindRoomRoomIdAsync(string RoomId) {
            return base.Channel.FindRoomRoomIdAsync(RoomId);
        }
    }
}
