//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.CustomerRegistrationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap")]
    public interface CustomerRegistrationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCustomer", ReplyAction="*")]
        ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponse insertCustomer(ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponse> insertCustomerAsync(ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCustomer", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequestBody Body;
        
        public insertCustomerRequest() {
        }
        
        public insertCustomerRequest(ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ConfirmPassword;
        
        public insertCustomerRequestBody() {
        }
        
        public insertCustomerRequestBody(string Name, string Email, string Address, string Phonenumber, string Password, string ConfirmPassword) {
            this.Name = Name;
            this.Email = Email;
            this.Address = Address;
            this.Phonenumber = Phonenumber;
            this.Password = Password;
            this.ConfirmPassword = ConfirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponseBody Body;
        
        public insertCustomerResponse() {
        }
        
        public insertCustomerResponse(ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCustomerResult;
        
        public insertCustomerResponseBody() {
        }
        
        public insertCustomerResponseBody(string insertCustomerResult) {
            this.insertCustomerResult = insertCustomerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerRegistrationWebServiceSoapChannel : ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerRegistrationWebServiceSoapClient : System.ServiceModel.ClientBase<ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap>, ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap {
        
        public CustomerRegistrationWebServiceSoapClient() {
        }
        
        public CustomerRegistrationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerRegistrationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerRegistrationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerRegistrationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponse ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap.insertCustomer(ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest request) {
            return base.Channel.insertCustomer(request);
        }
        
        public string insertCustomer(string Name, string Email, string Address, string Phonenumber, string Password, string ConfirmPassword) {
            ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest inValue = new ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest();
            inValue.Body = new ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Email = Email;
            inValue.Body.Address = Address;
            inValue.Body.Phonenumber = Phonenumber;
            inValue.Body.Password = Password;
            inValue.Body.ConfirmPassword = ConfirmPassword;
            ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponse retVal = ((ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap)(this)).insertCustomer(inValue);
            return retVal.Body.insertCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponse> ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap.insertCustomerAsync(ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest request) {
            return base.Channel.insertCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.CustomerRegistrationServiceReference.insertCustomerResponse> insertCustomerAsync(string Name, string Email, string Address, string Phonenumber, string Password, string ConfirmPassword) {
            ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest inValue = new ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequest();
            inValue.Body = new ClientApplication.CustomerRegistrationServiceReference.insertCustomerRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Email = Email;
            inValue.Body.Address = Address;
            inValue.Body.Phonenumber = Phonenumber;
            inValue.Body.Password = Password;
            inValue.Body.ConfirmPassword = ConfirmPassword;
            return ((ClientApplication.CustomerRegistrationServiceReference.CustomerRegistrationWebServiceSoap)(this)).insertCustomerAsync(inValue);
        }
    }
}
