//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ClientApplication.RegistrationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationServiceReference.RegistrationWebServiceasmxSoap")]
    public interface RegistrationWebServiceasmxSoap {
        
        // CODEGEN: Generating message contract since element name AutoHotelIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoHotelId", ReplyAction="*")]
        ClientApplication.RegistrationServiceReference.AutoHotelIdResponse AutoHotelId(ClientApplication.RegistrationServiceReference.AutoHotelIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoHotelId", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegistrationServiceReference.AutoHotelIdResponse> AutoHotelIdAsync(ClientApplication.RegistrationServiceReference.AutoHotelIdRequest request);
        
        // CODEGEN: Generating message contract since element name HotelId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertHotel", ReplyAction="*")]
        ClientApplication.RegistrationServiceReference.insertHotelResponse insertHotel(ClientApplication.RegistrationServiceReference.insertHotelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegistrationServiceReference.insertHotelResponse> insertHotelAsync(ClientApplication.RegistrationServiceReference.insertHotelRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoHotelIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoHotelId", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegistrationServiceReference.AutoHotelIdRequestBody Body;
        
        public AutoHotelIdRequest() {
        }
        
        public AutoHotelIdRequest(ClientApplication.RegistrationServiceReference.AutoHotelIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoHotelIdRequestBody {
        
        public AutoHotelIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoHotelIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoHotelIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegistrationServiceReference.AutoHotelIdResponseBody Body;
        
        public AutoHotelIdResponse() {
        }
        
        public AutoHotelIdResponse(ClientApplication.RegistrationServiceReference.AutoHotelIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoHotelIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoHotelIdResult;
        
        public AutoHotelIdResponseBody() {
        }
        
        public AutoHotelIdResponseBody(string AutoHotelIdResult) {
            this.AutoHotelIdResult = AutoHotelIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertHotelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertHotel", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegistrationServiceReference.insertHotelRequestBody Body;
        
        public insertHotelRequest() {
        }
        
        public insertHotelRequest(ClientApplication.RegistrationServiceReference.insertHotelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertHotelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HotelId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ConfirmPassword;
        
        public insertHotelRequestBody() {
        }
        
        public insertHotelRequestBody(string HotelId, string HotelName, string Email, string Address, string Phonenumber, string Location, string Password, string ConfirmPassword) {
            this.HotelId = HotelId;
            this.HotelName = HotelName;
            this.Email = Email;
            this.Address = Address;
            this.Phonenumber = Phonenumber;
            this.Location = Location;
            this.Password = Password;
            this.ConfirmPassword = ConfirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertHotelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertHotelResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegistrationServiceReference.insertHotelResponseBody Body;
        
        public insertHotelResponse() {
        }
        
        public insertHotelResponse(ClientApplication.RegistrationServiceReference.insertHotelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertHotelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertHotelResult;
        
        public insertHotelResponseBody() {
        }
        
        public insertHotelResponseBody(string insertHotelResult) {
            this.insertHotelResult = insertHotelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationWebServiceasmxSoapChannel : ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationWebServiceasmxSoapClient : System.ServiceModel.ClientBase<ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap>, ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap {
        
        public RegistrationWebServiceasmxSoapClient() {
        }
        
        public RegistrationWebServiceasmxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationWebServiceasmxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceasmxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceasmxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegistrationServiceReference.AutoHotelIdResponse ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap.AutoHotelId(ClientApplication.RegistrationServiceReference.AutoHotelIdRequest request) {
            return base.Channel.AutoHotelId(request);
        }
        
        public string AutoHotelId() {
            ClientApplication.RegistrationServiceReference.AutoHotelIdRequest inValue = new ClientApplication.RegistrationServiceReference.AutoHotelIdRequest();
            inValue.Body = new ClientApplication.RegistrationServiceReference.AutoHotelIdRequestBody();
            ClientApplication.RegistrationServiceReference.AutoHotelIdResponse retVal = ((ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap)(this)).AutoHotelId(inValue);
            return retVal.Body.AutoHotelIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegistrationServiceReference.AutoHotelIdResponse> ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap.AutoHotelIdAsync(ClientApplication.RegistrationServiceReference.AutoHotelIdRequest request) {
            return base.Channel.AutoHotelIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegistrationServiceReference.AutoHotelIdResponse> AutoHotelIdAsync() {
            ClientApplication.RegistrationServiceReference.AutoHotelIdRequest inValue = new ClientApplication.RegistrationServiceReference.AutoHotelIdRequest();
            inValue.Body = new ClientApplication.RegistrationServiceReference.AutoHotelIdRequestBody();
            return ((ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap)(this)).AutoHotelIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegistrationServiceReference.insertHotelResponse ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap.insertHotel(ClientApplication.RegistrationServiceReference.insertHotelRequest request) {
            return base.Channel.insertHotel(request);
        }
        
        public string insertHotel(string HotelId, string HotelName, string Email, string Address, string Phonenumber, string Location, string Password, string ConfirmPassword) {
            ClientApplication.RegistrationServiceReference.insertHotelRequest inValue = new ClientApplication.RegistrationServiceReference.insertHotelRequest();
            inValue.Body = new ClientApplication.RegistrationServiceReference.insertHotelRequestBody();
            inValue.Body.HotelId = HotelId;
            inValue.Body.HotelName = HotelName;
            inValue.Body.Email = Email;
            inValue.Body.Address = Address;
            inValue.Body.Phonenumber = Phonenumber;
            inValue.Body.Location = Location;
            inValue.Body.Password = Password;
            inValue.Body.ConfirmPassword = ConfirmPassword;
            ClientApplication.RegistrationServiceReference.insertHotelResponse retVal = ((ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap)(this)).insertHotel(inValue);
            return retVal.Body.insertHotelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegistrationServiceReference.insertHotelResponse> ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap.insertHotelAsync(ClientApplication.RegistrationServiceReference.insertHotelRequest request) {
            return base.Channel.insertHotelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegistrationServiceReference.insertHotelResponse> insertHotelAsync(string HotelId, string HotelName, string Email, string Address, string Phonenumber, string Location, string Password, string ConfirmPassword) {
            ClientApplication.RegistrationServiceReference.insertHotelRequest inValue = new ClientApplication.RegistrationServiceReference.insertHotelRequest();
            inValue.Body = new ClientApplication.RegistrationServiceReference.insertHotelRequestBody();
            inValue.Body.HotelId = HotelId;
            inValue.Body.HotelName = HotelName;
            inValue.Body.Email = Email;
            inValue.Body.Address = Address;
            inValue.Body.Phonenumber = Phonenumber;
            inValue.Body.Location = Location;
            inValue.Body.Password = Password;
            inValue.Body.ConfirmPassword = ConfirmPassword;
            return ((ClientApplication.RegistrationServiceReference.RegistrationWebServiceasmxSoap)(this)).insertHotelAsync(inValue);
        }

        internal string insertHotel(string text1, string text2, string text3, string text4, string text5, string text6, string text7)
        {
            throw new NotImplementedException();
        }
    }
}
